# -*- coding: utf-8 -*-
"""Streamlit_final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DtMHwRZxOTRS_D50XcsWv9LK8iyGADJP
"""

import streamlit as st
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
import numpy as np
import pickle

st.set_page_config(layout="wide")

with open("styles.css") as f:
    st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)

st.markdown("""
<style>

[data-testid="stAppViewContainer"]{
   background-color: #FAFFE6;
   textColor = "#000000"
}

[data-testid="stHeader"] {
background-color: rgba(0, 0, 0, 0);
}

[data-testid="stSidebar"] {
    background-color: #8EA140;
    textColor = "#000000"
}


</style>
""", unsafe_allow_html=True)

st.sidebar.title('**Options**')

pageselected = st.sidebar.selectbox('', ['Home','Potentials prediction'])


# Initialize session state variables
if 'selected_elements' not in st.session_state:
    st.session_state.selected_elements = []
if 'selected_material' not in st.session_state:
    st.session_state.selected_material = []

if 'sel_material' not in st.session_state:
    st.session_state.sel_material = []
if 'sel_material' not in st.session_state:
    st.session_state.sel_material = []


if 'sel_El_conc' not in st.session_state:
    st.session_state.sel_El_conc = []
if 'sel_pH' not in st.session_state:
    st.session_state.sel_pH = []
if 'sel_concentration' not in st.session_state:
    st.session_state.sel_concentration = []
if 'sel_selec_electrolyte' not in st.session_state:
    st.session_state.sel_selec_electrolyte = []
if 'sel_option_reference' not in st.session_state:
    st.session_state.sel_option_reference = []
if 'sel_option_analyte' not in st.session_state:
    st.session_state.sel_option_analyte = []

if pageselected == 'Home' :
    st.image("https://github.com/TWvonZuben/Streamlit/blob/main/Screenshot%20from%202024-01-15%2017-28-00.png?raw=true")

    st.header('Welcome to CAPER!', divider='rainbow')

    st.subheader("This tool was created to assist electrochemical scientists in predicting the results of the onset and oxidation potential of the electrooxidation of methanol and ethanol reactions. The work is better explained in the article 'Machine Learning Predictions of Onset and Oxidation Potentials for Methanol and Ethanol Electrooxidation: Comprehensive Analysis and Experimental Validation' and is based on machine learning models that utilize information from electrochemical reactions and electrode materials obtained from the literature to predict potentials.")
    st.subheader("The periodic table below illustrates the distribution of chemical elements used in working electrodes, as presented in the database that feeds the model. Consequently, we expect better predictions for materials with more information available in the literature and, consequently, in the database. Additionally, it is more probable that the prediction will be more accurate for methanol oxidation, as 70% of the database information is related to this analyte. The RMSE of the models is 0.169 V for oxidation potentials and 0.101 V for onset potentials.")

    st.image("https://github.com/TWvonZuben/Streamlit/blob/main/table.png?raw=true", width=1200)

    st.subheader("The initiative aims to aid and accelerate the study and discovery of new electrode materials for use in this process! If you encounter any problems or have any suggestions, please feel free to contact us at thevonzuben@gmail.com :flag-br:")
    st.subheader("The tools are simple and intuitive to use, but for optimal use and to avoid mistakes, please read the instructions provided below.")

    st.header('Instructions', divider='rainbow')

    st.subheader(":test_tube: To use the tool, first, select the option 'Potential predictions' on the left sidebar. After that, the options 'Reaction Conditions' and 'Working Electrode descrition' will appear.")
    st.subheader(":test_tube: Under 'Reaction Conditions', you must choose the electrolyte used in the reaction and its concentration. Additionally, select the pH of the solution. Choose the analyte you want to oxidize (methanol or ethanol) and its concentration. Finally, select the reference electrode you are using.")
    st.subheader(":test_tube: Under 'Working Electrode descrition', you must choose the chemical element used in the Working Electrode and in the Deposition selecting the elements in the periodic tables.")
    st.subheader(":eyes: If you want to clear all selected elements from the Periodic Table, simply click on 'Reset' in the bottom right corner.")
    st.subheader(":eyes: In the case of Nitrogen (N) and Carbon (C), options to be chosen will appear on the left side after selecting these elements.")

    st.subheader(":red[Attention!] If there is any material deposited on the Working Electrode, complete the 'Deposited material' field as you did for 'Working Electrode material'.")

if pageselected == 'Potentials prediction':

    parameters_selection = st.sidebar.radio('', ['Reactions conditions', 'Working Electrode descrition'])

    if parameters_selection == 'Reactions conditions':

        st.header('Potentials prediction', divider='rainbow')
        st.subheader('Choose the parameters used')

        options_electrolyte = ['KOH', 'NaOH', 'KNO3', 'phosphate','H2SO4', 'HClO4', 'HCl', 'Other']
        st.session_state.sel_selec_electrolyte = st.selectbox('**Select the :red[electrolyte]**', options_electrolyte)

        st.session_state.sel_El_conc = st.number_input('**Enter the :red[electrolyte concentration] value (mol/L)**',
                                  min_value=0.001, max_value=10.000, value=1.000, step=0.001)
        st.session_state.sel_pH = st.slider('**Select the :red[pH] value**', min_value=0.0, max_value=14.0, value=7.0, step=0.1)

        options_analyte = ['Methanol', 'Ethanol']
        st.session_state.sel_option_analyte = st.selectbox('**Select the :red[analyte]**', options_analyte)

        st.session_state.sel_concentration = st.number_input('**Enter the value of the :red[analyte concentration] (mol/L)**:', min_value=0.001, max_value=10.000, value=1.000, step=0.001)

        options_reference = ['RHE', 'SCE', 'NHE', 'SHE','Ag/AgCl', 'Hg/HgO', 'MMS', 'MMO', 'Other']
        st.session_state.sel_option_reference = st.selectbox('**Select the :red[Reference Electrode]**', options_reference)


    st.sidebar.subheader('Selected information:')

    st.sidebar.write(f'**Electrolyte:** {st.session_state.sel_selec_electrolyte} ({st.session_state.sel_El_conc} mol/L)')
    st.sidebar.write(f'**pH:** {st.session_state.sel_pH}')
    st.sidebar.write(f'**Analyte:** {st.session_state.sel_option_analyte} ({st.session_state.sel_concentration} mol/L)')
    st.sidebar.write(f'**Reference electrode:** {st.session_state.sel_option_reference}')